Tugas Kelompok Minggu 3


*   Revina Angelica
*   Gracelinda Chrisageulis



In [11]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import numpy as np

# Tambah data ke-21
X1 = np.random.normal(loc=1, scale=10, size=(1000, 1))

# Generate a synthetic classification dataset
X2, y = make_classification(n_samples=1000, n_features=20, n_informative=10, n_redundant=5, n_classes=2, random_state=42)

#Gabungkan data
X = np.hstack((X1, X2))

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (700, 21)
Shape of X_test: (300, 21)
Shape of y_train: (700,)
Shape of y_test: (300,)


In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Initialize the Sequential model
model = Sequential()

# Add the input layer (Dense layer with input_shape matching the number of features)
model.add(Dense(units=64, input_shape=(X_train.shape[1],), activation='relu'))

# Add a hidden layer
model.add(Dense(units=32, activation='relu'))

# Add the output layer (1 unit with sigmoid activation for binary classification)
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary to display the architecture
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,521 (13.75 KB)

 Trainable params: 3,521 (13.75 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Initialize the Sequential model with an Input layer
model = Sequential([
    Input(shape=(X_train.shape[1],)) # Explicitly define input shape
])

# Add the first hidden layer
model.add(Dense(units=64, activation='relu'))

# Add a second hidden layer
model.add(Dense(units=32, activation='relu'))

# Add the output layer (1 unit with sigmoid activation for binary classification)
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary to display the architecture
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,521 (13.75 KB)

 Trainable params: 3,521 (13.75 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print("Model compiled successfully with Adam optimizer, binary crossentropy loss, and accuracy metric.")

Model compiled successfully with Adam optimizer, binary crossentropy loss, and accuracy metric.


In [15]:
history = model.fit(X_train, y_train, epochs=5, batch_size=16, validation_split=0.2)
print("Model training complete. Training history stored in 'history' variable.")

Epoch 1/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5436 - loss: 0.8179 - val_accuracy: 0.7357 - val_loss: 0.5629
Epoch 2/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7992 - loss: 0.4764 - val_accuracy: 0.7929 - val_loss: 0.4391
Epoch 3/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8986 - loss: 0.3424 - val_accuracy: 0.8429 - val_loss: 0.3786
Epoch 4/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9256 - loss: 0.2651 - val_accuracy: 0.8786 - val_loss: 0.3212
Epoch 5/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9350 - loss: 0.2230 - val_accuracy: 0.8786 - val_loss: 0.2980
Model training complete. Training history stored in 'history' variable.


In [16]:
y_pred_proba = model.predict(X_test)
y_pred_classes = (y_pred_proba > 0.5).astype(int)

print("Predictions made successfully. First 5 predicted probabilities:")
print(y_pred_proba[:5].flatten())
print("First 5 predicted classes:")
print(y_pred_classes[:5].flatten())

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 
Predictions made successfully. First 5 predicted probabilities:
[0.72658604 0.01817548 0.5209945  0.928425   0.02139535]
First 5 predicted classes:
[1 0 1 1 0]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# Calculate Confusion Matrix
cm = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(cm)

# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"\nAccuracy: {accuracy:.4f}")

# Calculate Precision
precision = precision_score(y_test, y_pred_classes)
print(f"Precision: {precision:.4f}")

# Calculate Recall
recall = recall_score(y_test, y_pred_classes)
print(f"Recall: {recall:.4f}")

# Calculate F1-Score
f1 = f1_score(y_test, y_pred_classes)
print(f"F1-Score: {f1:.4f}")

Confusion Matrix:
[[138  22]
 [ 13 127]]

Accuracy: 0.8833
Precision: 0.8523
Recall: 0.9071
F1-Score: 0.8789


In [18]:
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
print("Model training complete. Training history stored in 'history' variable.")

Epoch 1/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9362 - loss: 0.2196 - val_accuracy: 0.9000 - val_loss: 0.2807
Epoch 2/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1917 - val_accuracy: 0.9143 - val_loss: 0.2623
Epoch 3/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9545 - loss: 0.1712 - val_accuracy: 0.9143 - val_loss: 0.2475
Epoch 4/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9581 - loss: 0.1640 - val_accuracy: 0.8929 - val_loss: 0.2556
Epoch 5/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9482 - loss: 0.1643 - val_accuracy: 0.9071 - val_loss: 0.2391
Epoch 6/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9610 - loss: 0.1403 - val_accuracy: 0.9143 - val_loss: 0.2267
Epoch 7/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9628 - loss: 0.1289 - val_accuracy: 0.9143 - val_loss: 0.2258
Epoch 8/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9603 - loss: 0.1285 - val_accuracy: 0.9000 - val_loss:

In [19]:
y_pred_proba = model.predict(X_test)
y_pred_classes = (y_pred_proba > 0.5).astype(int)

print("Predictions made successfully. First 5 predicted probabilities:")
print(y_pred_proba[:5].flatten())
print("First 5 predicted classes:")
print(y_pred_classes[:5].flatten())

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Predictions made successfully. First 5 predicted probabilities:
[3.989931e-01 6.751511e-03 6.425114e-01 9.924807e-01 7.122198e-04]
First 5 predicted classes:
[0 0 1 1 0]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# Calculate Confusion Matrix
cm = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(cm)

# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"\nAccuracy: {accuracy:.4f}")

# Calculate Precision
precision = precision_score(y_test, y_pred_classes)
print(f"Precision: {precision:.4f}")

# Calculate Recall
recall = recall_score(y_test, y_pred_classes)
print(f"Recall: {recall:.4f}")

# Calculate F1-Score
f1 = f1_score(y_test, y_pred_classes)
print(f"F1-Score: {f1:.4f}")

Confusion Matrix:
[[143  17]
 [ 11 129]]

Accuracy: 0.9067
Precision: 0.8836
Recall: 0.9214
F1-Score: 0.9021
