Tugas Kelompok Minggu 3


*   Revina Angelica
*   Gracelinda Chrisageulis



In [8]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import numpy as np

# Tambah data ke-21
X1 = np.random.normal(loc=1, scale=10, size=(1000, 1))

# Generate a synthetic classification dataset
X2, y = make_classification(n_samples=1000, n_features=20, n_informative=10, n_redundant=5, n_classes=2, random_state=42)

#Gabungkan data
X = np.hstack((X1, X2))

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (700, 21)
Shape of X_test: (300, 21)
Shape of y_train: (700,)
Shape of y_test: (300,)


In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Initialize the Sequential model
model = Sequential()

# Add the input layer (Dense layer with input_shape matching the number of features)
model.add(Dense(units=64, input_shape=(X_train.shape[1],), activation='relu'))

# Add a hidden layer
model.add(Dense(units=32, activation='relu'))

# Add the output layer (1 unit with sigmoid activation for binary classification)
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary to display the architecture
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,521 (13.75 KB)

 Trainable params: 3,521 (13.75 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Initialize the Sequential model with an Input layer
model = Sequential([
    Input(shape=(X_train.shape[1],)) # Explicitly define input shape
])

# Add the first hidden layer
model.add(Dense(units=64, activation='relu'))

# Add a second hidden layer
model.add(Dense(units=32, activation='relu'))

# Add the output layer (1 unit with sigmoid activation for binary classification)
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary to display the architecture
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,521 (13.75 KB)

 Trainable params: 3,521 (13.75 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print("Model compiled successfully with Adam optimizer, binary crossentropy loss, and accuracy metric.")

Model compiled successfully with Adam optimizer, binary crossentropy loss, and accuracy metric.


In [12]:
history = model.fit(X_train, y_train, epochs=5, batch_size=16, validation_split=0.2)
print("Model training complete. Training history stored in 'history' variable.")

Epoch 1/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5828 - loss: 0.7206 - val_accuracy: 0.7571 - val_loss: 0.5416
Epoch 2/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7727 - loss: 0.4579 - val_accuracy: 0.8214 - val_loss: 0.4505
Epoch 3/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8813 - loss: 0.3558 - val_accuracy: 0.8500 - val_loss: 0.4045
Epoch 4/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8736 - loss: 0.3159 - val_accuracy: 0.8429 - val_loss: 0.3626
Epoch 5/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9187 - loss: 0.2568 - val_accuracy: 0.8500 - val_loss: 0.3241
Model training complete. Training history stored in 'history' variable.


In [13]:
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
print("Model training complete. Training history stored in 'history' variable.")

Epoch 1/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9330 - loss: 0.2123 - val_accuracy: 0.8571 - val_loss: 0.3106
Epoch 2/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9502 - loss: 0.2024 - val_accuracy: 0.8643 - val_loss: 0.3009
Epoch 3/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9444 - loss: 0.1903 - val_accuracy: 0.8714 - val_loss: 0.2906
Epoch 4/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9619 - loss: 0.1592 - val_accuracy: 0.8643 - val_loss: 0.2837
Epoch 5/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9583 - loss: 0.1582 - val_accuracy: 0.8786 - val_loss: 0.2728
Epoch 6/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9736 - loss: 0.1376 - val_accuracy: 0.8857 - val_loss: 0.2635
Epoch 7/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9614 - loss: 0.1411 - val_accuracy: 0.8857 - val_loss: 0.2611
Epoch 8/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9753 - loss: 0.1109 - val_accuracy: 0.8857 - val_loss:

In [14]:
y_pred_proba = model.predict(X_test)
y_pred_classes = (y_pred_proba > 0.5).astype(int)

print("Predictions made successfully. First 5 predicted probabilities:")
print(y_pred_proba[:5].flatten())
print("First 5 predicted classes:")
print(y_pred_classes[:5].flatten())

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 
Predictions made successfully. First 5 predicted probabilities:
[0.27940175 0.00323574 0.7185795  0.94837034 0.00111273]
First 5 predicted classes:
[0 0 1 1 0]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# Calculate Confusion Matrix
cm = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(cm)

# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"\nAccuracy: {accuracy:.4f}")

# Calculate Precision
precision = precision_score(y_test, y_pred_classes)
print(f"Precision: {precision:.4f}")

# Calculate Recall
recall = recall_score(y_test, y_pred_classes)
print(f"Recall: {recall:.4f}")

# Calculate F1-Score
f1 = f1_score(y_test, y_pred_classes)
print(f"F1-Score: {f1:.4f}")

Confusion Matrix:
[[145  15]
 [ 13 127]]

Accuracy: 0.9067
Precision: 0.8944
Recall: 0.9071
F1-Score: 0.9007
